coverage:
  status:
    project:
      default:
        target: 80%
    patch:
      frontend:
        threshold: 0.01%
        flags:
          - frontend
      backend:
        flags:
          - backend 

github_checks:
    annotations: true
  
flags:
  frontend:
    carryforward: true
    paths: 
      - frontend/
  backend:
    carryforward: true
    paths: 
      - backend/