coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      backend:
        target: auto
        threshold: 1%
        flags:
          - backend
      frontend:
        target: auto
        threshold: 1%
        flags:
          - frontend
  layout: "newheader, diff, flags, files"
  require_changes: false
  require_base: false
  show_carryforward_flags: true
