codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
      backend:
        target: auto
        threshold: 1%
        flags:
          - backend
      frontend:
        target: auto
        threshold: 1%
        flags:
          - frontend
    patch:
      default:
        target: 80%
        threshold: 1%
        informational: true

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  show_carryforward_flags: true

flags:
  backend:
    paths:
      - backend/
    carryforward: true
  frontend:
    paths:
      - frontend/
    carryforward: true